/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vehicle_management;

import com.main.Main_Menu;
import common.CommonM;
import common.DB;
import java.awt.Color;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author geeth
 */
public class Details extends javax.swing.JFrame {

    /**
     * Creates new form Vehicle_Management
     */
    public Details() {
        initComponents();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        CommonM.setFullScreen(this);
        txtVehicleId.setEditable(false);
        txtOilCapa.setEditable(false);
        txtRegNo.setEditable(false);
        txtModel.setEditable(false);
        txtNextService.setEditable(false);
          CommonM.tableSettings(tb1);
          CommonM.tableSettings(tb2);

        
    }

    Details(String vehicleId) {
       initComponents();
          this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
               CommonM.setFullScreen(this);
        txtVehicleId.setEditable(false);
        txtOilCapa.setEditable(false);
        txtRegNo.setEditable(false);
        txtModel.setEditable(false);
        txtNextService.setEditable(false);
          CommonM.tableSettings(tb1);
            CommonM.tableSettings(tb2);
       loadData(vehicleId);
    }
       String vehicleId1;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        ReForm = new javax.swing.JLayeredPane();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb2 = new javax.swing.JTable();
        ReForm1 = new javax.swing.JLayeredPane();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb1 = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        txtNextService = new javax.swing.JTextField();
        txtVehicleId = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtRegNo = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtModel = new javax.swing.JTextField();
        txtOilCapa = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLayeredPane1.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ReForm.setBackground(new java.awt.Color(255, 255, 255));
        ReForm.setOpaque(true);
        ReForm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(204, 0, 51));
        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Repair Details");
        jLabel5.setOpaque(true);
        ReForm.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 69));

        tb2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Repair Date", "Charges", "Discription", "Data Time"
            }
        ));
        jScrollPane2.setViewportView(tb2);

        ReForm.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 920, 870));

        jLayeredPane1.add(ReForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 70, 940, 970));

        ReForm1.setBackground(new java.awt.Color(255, 255, 255));
        ReForm1.setOpaque(true);
        ReForm1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setBackground(new java.awt.Color(204, 0, 51));
        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Service Details");
        jLabel6.setOpaque(true);
        ReForm1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 69));

        tb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Service Date", "Meter", "Service Charges", "Discription", "Data Time"
            }
        ));
        tb1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb1);

        ReForm1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 920, 810));

        jLabel12.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel12.setText("Next Service Kilometer");
        jLabel12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel12KeyPressed(evt);
            }
        });
        ReForm1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 230, 42));

        txtNextService.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtNextService.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtNextService.setOpaque(false);
        txtNextService.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtNextServiceMouseReleased(evt);
            }
        });
        txtNextService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNextServiceActionPerformed(evt);
            }
        });
        txtNextService.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNextServiceKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNextServiceKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNextServiceKeyTyped(evt);
            }
        });
        ReForm1.add(txtNextService, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 670, 43));

        jLayeredPane1.add(ReForm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 940, 970));

        txtVehicleId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtVehicleId.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtVehicleId.setOpaque(false);
        txtVehicleId.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtVehicleIdMouseReleased(evt);
            }
        });
        txtVehicleId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVehicleIdActionPerformed(evt);
            }
        });
        txtVehicleId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtVehicleIdKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtVehicleIdKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtVehicleIdKeyTyped(evt);
            }
        });
        jLayeredPane1.add(txtVehicleId, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 330, 43));

        jLabel13.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel13.setText("Id");
        jLabel13.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel13KeyPressed(evt);
            }
        });
        jLayeredPane1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 110, 42));

        jLabel14.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel14.setText("Reg No");
        jLabel14.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel14KeyPressed(evt);
            }
        });
        jLayeredPane1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 110, 42));

        txtRegNo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtRegNo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtRegNo.setOpaque(false);
        txtRegNo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtRegNoMouseReleased(evt);
            }
        });
        txtRegNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegNoActionPerformed(evt);
            }
        });
        txtRegNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtRegNoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRegNoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRegNoKeyTyped(evt);
            }
        });
        jLayeredPane1.add(txtRegNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 330, 43));

        jLabel15.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel15.setText("Model");
        jLabel15.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel15KeyPressed(evt);
            }
        });
        jLayeredPane1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 10, 110, 42));

        txtModel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtModel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtModel.setOpaque(false);
        txtModel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtModelMouseReleased(evt);
            }
        });
        txtModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModelActionPerformed(evt);
            }
        });
        txtModel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtModelKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtModelKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtModelKeyTyped(evt);
            }
        });
        jLayeredPane1.add(txtModel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 10, 330, 43));

        txtOilCapa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtOilCapa.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtOilCapa.setOpaque(false);
        txtOilCapa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtOilCapaMouseReleased(evt);
            }
        });
        txtOilCapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOilCapaActionPerformed(evt);
            }
        });
        txtOilCapa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtOilCapaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtOilCapaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtOilCapaKeyTyped(evt);
            }
        });
        jLayeredPane1.add(txtOilCapa, new org.netbeans.lib.awtextra.AbsoluteConstraints(1550, 10, 330, 43));

        jLabel16.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel16.setText("Oil Capa");
        jLabel16.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel16KeyPressed(evt);
            }
        });
        jLayeredPane1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1430, 10, 110, 42));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel12KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel12KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12KeyPressed

    private void txtNextServiceMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNextServiceMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNextServiceMouseReleased

    private void txtNextServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNextServiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNextServiceActionPerformed

    private void txtNextServiceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNextServiceKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNextServiceKeyPressed

    private void txtNextServiceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNextServiceKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNextServiceKeyReleased

    private void txtNextServiceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNextServiceKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNextServiceKeyTyped

    private void txtVehicleIdMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtVehicleIdMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVehicleIdMouseReleased

    private void txtVehicleIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVehicleIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVehicleIdActionPerformed

    private void txtVehicleIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVehicleIdKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVehicleIdKeyPressed

    private void txtVehicleIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVehicleIdKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVehicleIdKeyReleased

    private void txtVehicleIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVehicleIdKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVehicleIdKeyTyped

    private void jLabel13KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel13KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel13KeyPressed

    private void jLabel14KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel14KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel14KeyPressed

    private void txtRegNoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRegNoMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegNoMouseReleased

    private void txtRegNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegNoActionPerformed

    private void txtRegNoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRegNoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegNoKeyPressed

    private void txtRegNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRegNoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegNoKeyReleased

    private void txtRegNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRegNoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegNoKeyTyped

    private void jLabel15KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel15KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel15KeyPressed

    private void txtModelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtModelMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModelMouseReleased

    private void txtModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModelActionPerformed

    private void txtModelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtModelKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModelKeyPressed

    private void txtModelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtModelKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModelKeyReleased

    private void txtModelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtModelKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModelKeyTyped

    private void txtOilCapaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtOilCapaMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOilCapaMouseReleased

    private void txtOilCapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOilCapaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOilCapaActionPerformed

    private void txtOilCapaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOilCapaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOilCapaKeyPressed

    private void txtOilCapaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOilCapaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOilCapaKeyReleased

    private void txtOilCapaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOilCapaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOilCapaKeyTyped

    private void jLabel16KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel16KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel16KeyPressed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
         new Vehicle_Management().setVisible(true);
        
    }//GEN-LAST:event_formWindowClosing

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
    
    }//GEN-LAST:event_formWindowClosed

    private void tb1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb1MouseClicked
          String meter =tb1.getValueAt(tb1.getSelectedRow(), 1).toString();
        new Service_Details(vehicleId1,meter).setVisible(true);
    }//GEN-LAST:event_tb1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane ReForm;
    private javax.swing.JLayeredPane ReForm1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tb1;
    private javax.swing.JTable tb2;
    public static javax.swing.JTextField txtModel;
    public static javax.swing.JTextField txtNextService;
    public static javax.swing.JTextField txtOilCapa;
    public static javax.swing.JTextField txtRegNo;
    public static javax.swing.JTextField txtVehicleId;
    // End of variables declaration//GEN-END:variables

    private void loadData(String vehicleId) {
        try {
            vehicleId1=vehicleId;
            vehicleData(vehicleId);
            serviceData(vehicleId);
           repairData(vehicleId);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void vehicleData(String vehicleId) {
        try {
            ResultSet search = DB.search("SELECT * FROM vehicle WHERE vehicle_id='"+vehicleId+"'");
            if(search.next()){
            txtVehicleId.setText(vehicleId);
            txtRegNo.setText(search.getString("province")+" "+search.getString("registration_number"));
            txtModel.setText(search.getString("model"));
            txtOilCapa.setText(search.getString("engine_oil_capa"));
            
            
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void serviceData(String vehicleId) {
        try {
               DefaultTableModel dtm =(DefaultTableModel) tb1.getModel();
           ResultSet search = DB.search("SELECT * FROM vehicle_service WHERE status=1 AND vehicle_id='"+vehicleId+"'");
           dtm.setRowCount(0);
           double lastMeter=0.0;
           double next=0.0;
           while(search.next()){
               Vector v = new Vector();
               v.add(search.getString("service_date"));
               v.add(search.getString("last_meter"));
               v.add(search.getString("service_charges"));
               v.add(search.getString("discription"));
                 v.add(search.getString("data_time"));
                 lastMeter=Double.parseDouble(search.getString("last_meter"));
                 next=Double.parseDouble(search.getString("next_service"));
               dtm.addRow(v);
               }
           txtNextService.setText(String.valueOf(lastMeter+next));
            
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void repairData(String vehicleId) {
        try {
               DefaultTableModel dtm =(DefaultTableModel) tb2.getModel();
           ResultSet search = DB.search("SELECT * FROM vehicle_repair WHERE status=1 AND vehicle_id='"+vehicleId+"'");
           dtm.setRowCount(0);
           while(search.next()){
               Vector v = new Vector();
               v.add(search.getString("id"));
               v.add(search.getString("repair_date"));
               v.add(search.getString("repair_charges"));
               v.add(search.getString("discription"));
                 v.add(search.getString("data_time"));
               dtm.addRow(v);
               }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

   

    
}
