package com.vehicle_management;

import static common.CommonM.checkNull;
import common.DB;
import common.SystemData;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.JOptionPane;

/**
 *
 * @author geeth
 */
public class Vehicle_Service extends javax.swing.JFrame {

    /**
     * Creates new form Start_Job
     */
    public Vehicle_Service() {
        initComponents();

        jScrollPane2.setVisible(false);
        txtSearch.grabFocus();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        txtRegNumber.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane2 = new javax.swing.JLayeredPane();
        ReForm = new javax.swing.JLayeredPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel9 = new javax.swing.JLabel();
        txtRegNumber = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtServiceCharge = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDiscription = new javax.swing.JTextArea();
        btnRegister3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtLastMeter = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtNextService = new javax.swing.JTextField();
        txtSearch = new javax.swing.JTextField();
        comboSearch = new javax.swing.JComboBox<>();
        lbFirstName1 = new javax.swing.JLabel();
        txtServiceDate = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLayeredPane2.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jLayeredPane2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ReForm.setBackground(new java.awt.Color(255, 255, 255));
        ReForm.setOpaque(true);
        ReForm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jList1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jList1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jList1KeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jList1);

        ReForm.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 260, 130));

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel9.setText("Service Date");
        jLabel9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel9KeyPressed(evt);
            }
        });
        ReForm.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 175, 42));

        txtRegNumber.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtRegNumber.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtRegNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegNumberActionPerformed(evt);
            }
        });
        txtRegNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtRegNumberKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRegNumberKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRegNumberKeyTyped(evt);
            }
        });
        ReForm.add(txtRegNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 450, 43));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel1.setText("Registration Number");
        ReForm.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 210, 43));

        jLabel5.setBackground(new java.awt.Color(204, 0, 51));
        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Vehicle Service");
        jLabel5.setOpaque(true);
        ReForm.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 69));

        txtServiceCharge.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtServiceCharge.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtServiceCharge.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtServiceChargeMouseReleased(evt);
            }
        });
        txtServiceCharge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtServiceChargeActionPerformed(evt);
            }
        });
        ReForm.add(txtServiceCharge, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 450, 43));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel2.setText("Last Meter");
        ReForm.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 190, 43));

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel10.setText("discreption");
        ReForm.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 175, 42));

        txtDiscription.setColumns(20);
        txtDiscription.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        txtDiscription.setRows(5);
        txtDiscription.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtDiscriptionMouseReleased(evt);
            }
        });
        txtDiscription.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDiscriptionKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(txtDiscription);

        ReForm.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, 450, 150));

        btnRegister3.setBackground(new java.awt.Color(0, 102, 204));
        btnRegister3.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 30)); // NOI18N
        btnRegister3.setForeground(new java.awt.Color(255, 255, 255));
        btnRegister3.setText("Add");
        btnRegister3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegister3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegister3MouseExited(evt);
            }
        });
        btnRegister3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegister3ActionPerformed(evt);
            }
        });
        ReForm.add(btnRegister3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 630, 210, 60));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel3.setText("Service Charges");
        ReForm.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 175, 43));

        txtLastMeter.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtLastMeter.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtLastMeter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtLastMeterMouseReleased(evt);
            }
        });
        txtLastMeter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastMeterActionPerformed(evt);
            }
        });
        txtLastMeter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLastMeterKeyTyped(evt);
            }
        });
        ReForm.add(txtLastMeter, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 450, 43));

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel11.setText("Next Service");
        jLabel11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel11KeyPressed(evt);
            }
        });
        ReForm.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 175, 42));

        txtNextService.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtNextService.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtNextService.setOpaque(false);
        txtNextService.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtNextServiceMouseReleased(evt);
            }
        });
        txtNextService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNextServiceActionPerformed(evt);
            }
        });
        txtNextService.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNextServiceKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNextServiceKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNextServiceKeyTyped(evt);
            }
        });
        ReForm.add(txtNextService, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 450, 43));

        txtSearch.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtSearch.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSearchKeyTyped(evt);
            }
        });
        ReForm.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 260, 43));

        comboSearch.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        comboSearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Reg Number", "Vehicle Id", "Model" }));
        comboSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSearchActionPerformed(evt);
            }
        });
        ReForm.add(comboSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 170, 40));

        lbFirstName1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        lbFirstName1.setText("Search By");
        ReForm.add(lbFirstName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 170, 42));

        txtServiceDate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtServiceDateMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtServiceDateMouseReleased(evt);
            }
        });
        ReForm.add(txtServiceDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 450, 40));

        jLayeredPane2.add(ReForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 750, 840));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 881, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtRegNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegNumberActionPerformed

    }//GEN-LAST:event_txtRegNumberActionPerformed

    private void txtServiceChargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtServiceChargeActionPerformed
      if(!txtServiceCharge.getText().equals("")){
      txtDiscription.grabFocus();
      }
    }//GEN-LAST:event_txtServiceChargeActionPerformed

    private void txtRegNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRegNumberKeyReleased

    }//GEN-LAST:event_txtRegNumberKeyReleased

    private void txtRegNumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRegNumberKeyTyped

    }//GEN-LAST:event_txtRegNumberKeyTyped

    private void btnRegister3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegister3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegister3MouseEntered

    private void btnRegister3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegister3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegister3MouseExited

    private void btnRegister3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegister3ActionPerformed
        try {
               if(!txtSearch.getText().equals("")){
                   ResultSet search = DB.search("SELECT * FROM vehicle WHERE vehicle_id='"+txtSearch.getText().toUpperCase()+"'");
            if(search.next()){
            addData();
            }else{
             JOptionPane.showMessageDialog(this, "Invalid Vehicle Id", "Error", JOptionPane.ERROR_MESSAGE);
             txtSearch.setText(null);
             txtSearch.grabFocus();
             
            }
        }
        } catch (Exception e) {
            e.printStackTrace();
        }
     
    }//GEN-LAST:event_btnRegister3ActionPerformed

    private void jLabel9KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel9KeyPressed

    }//GEN-LAST:event_jLabel9KeyPressed

    private void txtLastMeterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastMeterActionPerformed
         checkNull(txtLastMeter,"Next Service",txtServiceCharge);
    }//GEN-LAST:event_txtLastMeterActionPerformed

    private void txtLastMeterKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLastMeterKeyTyped

    }//GEN-LAST:event_txtLastMeterKeyTyped

    private void txtRegNumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRegNumberKeyPressed

    }//GEN-LAST:event_txtRegNumberKeyPressed

    private void txtLastMeterMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtLastMeterMouseReleased
         if(txtSearch.getText().equals("")){
       txtSearch.grabFocus();
       }else if(txtNextService.getText().equals("")){
       txtNextService.grabFocus();
       }
    }//GEN-LAST:event_txtLastMeterMouseReleased

    private void txtServiceChargeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtServiceChargeMouseReleased
       if(txtSearch.getText().equals("")){
       txtSearch.grabFocus();
       }else if(txtNextService.getText().equals("")){
       txtNextService.grabFocus();
       }else if(txtLastMeter.getText().equals("")){
       txtLastMeter.grabFocus();
       }
    }//GEN-LAST:event_txtServiceChargeMouseReleased

    private void txtDiscriptionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiscriptionKeyReleased

    }//GEN-LAST:event_txtDiscriptionKeyReleased

    private void txtDiscriptionMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDiscriptionMouseReleased


    }//GEN-LAST:event_txtDiscriptionMouseReleased

    private void jLabel11KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel11KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel11KeyPressed

    private void txtNextServiceMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNextServiceMouseReleased
      if(txtSearch.getText().equals("")){
       txtSearch.grabFocus();
       }
    }//GEN-LAST:event_txtNextServiceMouseReleased

    private void txtNextServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNextServiceActionPerformed
        checkNull(txtNextService,"Next Service",txtLastMeter);
    }//GEN-LAST:event_txtNextServiceActionPerformed

    private void txtNextServiceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNextServiceKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNextServiceKeyPressed

    private void txtNextServiceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNextServiceKeyReleased
      
    }//GEN-LAST:event_txtNextServiceKeyReleased

    private void txtNextServiceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNextServiceKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNextServiceKeyTyped

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        if (evt.getClickCount() == 2) {
             comboSearch.setSelectedIndex(1);
             String vehicleId=jList1.getSelectedValue().split(":")[0];
             txtSearch.setText(vehicleId);
            searchDetails(vehicleId);
            txtServiceDate.grabFocus();
        }
    }//GEN-LAST:event_jList1MouseClicked

    private void jList1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jList1KeyPressed
        if (evt.getKeyCode() == 10) {
                  comboSearch.setSelectedIndex(1);
             String vehicleId=jList1.getSelectedValue().split(":")[0];
             txtSearch.setText(vehicleId);
            searchDetails(vehicleId);
            txtServiceDate.grabFocus();
        }
    }//GEN-LAST:event_jList1KeyPressed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        searchVehicle();
        if (evt.getKeyCode() == 40) {
            jList1.setSelectedIndex(0);
            jList1.grabFocus();
        }
        if (txtSearch.getText().equals("")) {

        }
    }//GEN-LAST:event_txtSearchKeyReleased

    private void txtSearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchKeyTyped

    private void comboSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSearchActionPerformed
       jScrollPane2.setVisible(false);
       jScrollPane2.removeAll();
       txtSearch.setText(null);
       txtSearch.grabFocus();
    }//GEN-LAST:event_comboSearchActionPerformed

    private void txtServiceDateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtServiceDateMouseClicked
    
        
      
    }//GEN-LAST:event_txtServiceDateMouseClicked

    private void txtServiceDateMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtServiceDateMouseReleased
          if( txtSearch.getText().equals("")){
               txtServiceDate.setDate(null);
       txtSearch.grabFocus();
      
       }
    }//GEN-LAST:event_txtServiceDateMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vehicle_Service.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vehicle_Service.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vehicle_Service.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vehicle_Service.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vehicle_Service().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane ReForm;
    private javax.swing.JButton btnRegister3;
    public static javax.swing.JComboBox<String> comboSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane2;
    public static javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbFirstName1;
    private javax.swing.JTextArea txtDiscription;
    private javax.swing.JTextField txtLastMeter;
    public static javax.swing.JTextField txtNextService;
    public static javax.swing.JTextField txtRegNumber;
    public static javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtServiceCharge;
    private com.toedter.calendar.JDateChooser txtServiceDate;
    // End of variables declaration//GEN-END:variables

    private void searchVehicle() {
        try {

            if (!txtSearch.getText().trim().equals("")) {
                if (comboSearch.getSelectedItem().equals("Reg Number")) {
                    ResultSet rs = DB.search("SELECT * FROM vehicle WHERE status=1 AND registration_number  LIKE '" + txtSearch.getText().toUpperCase() + "%'");
                    Vector v = new Vector();
                    jScrollPane2.setVisible(false);
                    while (rs.next()) {
                        jScrollPane2.setVisible(true);
                        v.add(rs.getString("vehicle_id") + ": " + rs.getString("registration_number") + "  -  " + rs.getString("model"));
                    }
                    jList1.setListData(v);
                } else if (comboSearch.getSelectedItem().equals("Vehicle Id")) {
                    ResultSet rs = DB.search("SELECT * FROM vehicle WHERE status=1 AND vehicle_id  LIKE '" + txtSearch.getText().toUpperCase() + "%'");
                    Vector v = new Vector();
                    jScrollPane2.setVisible(false);
                    while (rs.next()) {
                        jScrollPane2.setVisible(true);
                        v.add(rs.getString("vehicle_id") + ": " + rs.getString("registration_number") + "  -  " + rs.getString("model"));
                    }
                    jList1.setListData(v);
                } else if (comboSearch.getSelectedItem().equals("Model")) {
                          ResultSet rs = DB.search("SELECT * FROM vehicle WHERE status=1 AND model  LIKE '" + txtSearch.getText().toUpperCase() + "%'");
                    Vector v = new Vector();
                    jScrollPane2.setVisible(false);
                    while (rs.next()) {
                        jScrollPane2.setVisible(true);
                        v.add(rs.getString("vehicle_id") + ": " + rs.getString("registration_number") + "  -  " + rs.getString("model"));
                    }
                    jList1.setListData(v);
                }
            } else {
                jScrollPane2.setVisible(false);

            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void searchDetails(String vehicleId) {
        try {
            ResultSet search = DB.search("SELECT * FROM vehicle WHERE status=1 AND vehicle_id='"+vehicleId+"'");
            if(search.next()){
            txtRegNumber.setText(search.getString("province")+" "+search.getString("registration_number"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    
    }

    private void addData() {
        try {
             String date = new SimpleDateFormat("yyyy-MM-dd- HH:mm:ss").format(new Date());
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String serviceDate =sdf.format(txtServiceDate.getDate());
            String description = null;
            if(txtDiscription.getText().equals("")){
            description="None";
            }else {
            description=txtDiscription.getText();
            }
            DB.iud("INSERT INTO vehicle_service(vehicle_id,service_date,next_service,last_meter,service_charges,discription,data_time,added_by,status) VALUES ('"+txtSearch.getText().toUpperCase()+"','"+serviceDate+"','"+txtNextService.getText()+"',"
                    + "'"+txtLastMeter.getText()+"','"+txtServiceCharge.getText()+"','"+description+"','"+date+"','"+SystemData.getemployee()+"','"+1+"')");
            clearFeald();
             JOptionPane.showMessageDialog(this, " successfull");
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void clearFeald() {
        txtDiscription.setText(null);
        txtLastMeter.setText(null);
        txtNextService.setText(null);
        txtRegNumber.setText(null);
        txtSearch.setText(null);
        txtServiceCharge.setText(null);
        txtServiceDate.setDate(null);
    }

}
