/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.employee_management;

import com.main.MD5;
import static common.CommonM.checkNull;
import common.DB;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.JOptionPane;

/**
 *
 * @author geeth
 */
public class Change_Password extends javax.swing.JFrame {

    /**
     * Creates new form Add_Customer_Befor_Start
     */
    public Change_Password() {
        initComponents();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
       jScrollPane1.setVisible(false);
        this.setResizable(false);
        txtSearch.grabFocus();
      editable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        ReForm = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        txtUserName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        comboSearch = new javax.swing.JComboBox<>();
        txtSearch = new javax.swing.JTextField();
        btnUpdte1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        passNew = new javax.swing.JPasswordField();
        passRe = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ReForm.setBackground(new java.awt.Color(255, 255, 255));
        ReForm.setOpaque(true);
        ReForm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jList1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jList1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jList1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        ReForm.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 290, -1));

        txtUserName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtUserName.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserNameActionPerformed(evt);
            }
        });
        txtUserName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUserNameKeyTyped(evt);
            }
        });
        ReForm.add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 440, 43));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel1.setText("New Password");
        ReForm.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 175, 43));

        jLabel5.setBackground(new java.awt.Color(204, 0, 51));
        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Edite Details");
        jLabel5.setOpaque(true);
        ReForm.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 69));

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel11.setText("Search By");
        ReForm.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 111, 110, 41));

        comboSearch.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        comboSearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "User Name", "Employee Id", "Nic Number" }));
        ReForm.add(comboSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 111, 137, 45));

        txtSearch.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtSearch.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSearchKeyTyped(evt);
            }
        });
        ReForm.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 113, 290, 43));

        btnUpdte1.setBackground(new java.awt.Color(0, 102, 204));
        btnUpdte1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 36)); // NOI18N
        btnUpdte1.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdte1.setText("Update");
        btnUpdte1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUpdte1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUpdte1MouseExited(evt);
            }
        });
        btnUpdte1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdte1ActionPerformed(evt);
            }
        });
        ReForm.add(btnUpdte1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 420, 204, -1));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel2.setText("User Name");
        ReForm.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 175, 43));

        passNew.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        passNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passNewActionPerformed(evt);
            }
        });
        ReForm.add(passNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 440, 40));

        passRe.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        passRe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                passReMouseReleased(evt);
            }
        });
        passRe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passReActionPerformed(evt);
            }
        });
        ReForm.add(passRe, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 440, 40));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel3.setText("Re-Enter");
        ReForm.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 175, 43));

        jLayeredPane1.add(ReForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 780, 780));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 872, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 872, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserNameActionPerformed
         checkNull(txtSearch,"Search",txtUserName);
    }//GEN-LAST:event_txtUserNameActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void txtSearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchKeyTyped

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
      searchData();
       if(evt.getKeyCode()==40){
        jList1.setSelectedIndex(0);
        jList1.grabFocus();
        }
    }//GEN-LAST:event_txtSearchKeyReleased

    private void btnUpdte1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdte1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdte1MouseEntered

    private void btnUpdte1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdte1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdte1MouseExited

    private void btnUpdte1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdte1ActionPerformed
       updateDetails();
    }//GEN-LAST:event_btnUpdte1ActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
             if(evt.getClickCount()==2){
            txtSearch.setText(jList1.getSelectedValue().split("-")[0]);
            jScrollPane1.setVisible(false);
            searchDetails();

        }
    }//GEN-LAST:event_jList1MouseClicked

    private void txtUserNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserNameKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserNameKeyTyped

    private void jList1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jList1KeyPressed
               if(evt.getKeyCode()==10){
            txtSearch.setText(jList1.getSelectedValue().split("-")[0]);
            jScrollPane1.setVisible(false);
            searchDetails();

        }
    }//GEN-LAST:event_jList1KeyPressed

    private void passNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passNewActionPerformed
          if(String.valueOf(passNew.getPassword()).equals("")){
      passNew.grabFocus();
     }else{
             passRe.grabFocus();
          }
     
    }//GEN-LAST:event_passNewActionPerformed

    private void passReActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passReActionPerformed
     updateDetails();
    }//GEN-LAST:event_passReActionPerformed

    private void passReMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passReMouseReleased
     if(String.valueOf(passNew.getPassword()).equals("")){
      passNew.grabFocus();
     }
    }//GEN-LAST:event_passReMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Change_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Change_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Change_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Change_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Change_Password().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane ReForm;
    private javax.swing.JButton btnUpdte1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> comboSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPasswordField passNew;
    private javax.swing.JPasswordField passRe;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables

    private void searchData() {
       if(comboSearch.getSelectedItem()=="User Name"){
        try {
            if(!txtSearch.getText().trim().equals("")){
                ResultSet rs=  DB.search("SELECT * FROM user_account WHERE user_name LIKE '"+txtSearch.getText().toUpperCase()+"%'");
                Vector v = new Vector();
                       jScrollPane1.setVisible(false);
                while(rs.next()){
                     jScrollPane1.setVisible(true);
                    v.add(rs.getString("employee_id")+"-"+rs.getString("user_name"));
                }
                jList1.setListData(v);
            }else{
            jScrollPane1.setVisible(false);
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
       }else if(comboSearch.getSelectedItem()=="Employee Id"){
        try {
            if(!txtSearch.getText().trim().equals("")){
                ResultSet rs=  DB.search("SELECT * FROM user_account WHERE employee_id LIKE '"+txtSearch.getText().toUpperCase()+"%'");
                Vector v = new Vector();
                       jScrollPane1.setVisible(false);
                while(rs.next()){
                     jScrollPane1.setVisible(true);
                    v.add(rs.getString("employee_id")+"-"+rs.getString("user_name"));
                }
                jList1.setListData(v);
            }else{
              jScrollPane1.setVisible(false);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
       
       }else if(comboSearch.getSelectedItem()=="Nic Number"){
            try {
            if(!txtSearch.getText().trim().equals("")){
                ResultSet rs=  DB.search("SELECT * FROM employee WHERE nic_number LIKE '"+txtSearch.getText().toUpperCase()+"%'");
                Vector v = new Vector();
                       jScrollPane1.setVisible(false);
                while(rs.next()){
                     jScrollPane1.setVisible(true);
                    v.add(rs.getString("employee_id")+"-"+rs.getString("first_name")+" "+rs.getString("last_name"));
                }
                jList1.setListData(v);
            }else{
             jScrollPane1.setVisible(false);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
       
       }
    }

 

    private void editable() {
      txtUserName.setEditable(false);
     
    }

    private void searchDetails() {
        try {
            ResultSet search = DB.search("SELECT * FROM user_account WHERE employee_id='"+txtSearch.getText().toUpperCase()+"'");
            if(search.next()){
            txtUserName.setText(search.getString("user_name"));
            passNew.grabFocus();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void updateDetails() {
        try{
            if(!txtSearch.getText().trim().equals("")){
                if(!String.valueOf(passNew.getPassword()).equals("")){
        if(String.valueOf(passNew.getPassword()).equals(String.valueOf(passRe.getPassword()))){
            ResultSet search = DB.search("SELECT * FROM employee WHERE employee_id='"+txtSearch.getText()+"'");
            if(search.next()){
        DB.iud("update user_account set password='"+MD5.getMd5(String.valueOf(passNew.getPassword()))+"' where employee_id='"+txtSearch.getText()+"'");
          JOptionPane.showMessageDialog(this, "successfull");
          clearFeald();
            }else{
             JOptionPane.showMessageDialog(this, "Invalid User Name", "Error",JOptionPane.ERROR_MESSAGE); 
             txtSearch.grabFocus();
            }
        }else{
          JOptionPane.showMessageDialog(this, "Cheack your password again.", "Error",JOptionPane.ERROR_MESSAGE); 
          passNew.setText(null);
          passRe.setText(null);
          passNew.grabFocus();
        }
                }else{
                 JOptionPane.showMessageDialog(this, "Empty Password. Try again", "Error",JOptionPane.ERROR_MESSAGE); 
                }
            }else{
                JOptionPane.showMessageDialog(this, "Invalid User Name", "Error",JOptionPane.ERROR_MESSAGE); 
            }
        }catch(Exception e){
                   JOptionPane.showMessageDialog(this, "Error Try Again", "Error",JOptionPane.ERROR_MESSAGE); 
        }
        
    }

    private void clearFeald() {
        txtSearch.setText(null);
        txtUserName.setText(null);
        txtSearch.grabFocus();
        passNew.setText(null);
        passRe.setText(null);
    }
}
