/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.employee_management;

import com.customer_management.*;
import common.CommonM;
import common.DB;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.JOptionPane;

/**
 *
 * @author geeth
 */
public class Edite_user_Acc extends javax.swing.JFrame {

    /**
     * Creates new form Add_Customer_Befor_Start
     */
    public Edite_user_Acc() {
        initComponents();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
       jScrollPane1.setVisible(false);
        this.setResizable(false);
        txtSearch.grabFocus();
      editable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        ReForm = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        redioInactive = new javax.swing.JRadioButton();
        redioActive = new javax.swing.JRadioButton();
        lbGender = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtType = new javax.swing.JTextField();
        lbFirstName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtUserName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        comboSearch = new javax.swing.JComboBox<>();
        txtSearch = new javax.swing.JTextField();
        btnUpdte1 = new javax.swing.JButton();
        txtEmployeeId = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ReForm.setBackground(new java.awt.Color(255, 255, 255));
        ReForm.setOpaque(true);
        ReForm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jList1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        ReForm.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 290, -1));

        buttonGroup1.add(redioInactive);
        redioInactive.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        redioInactive.setText("Inactive");
        ReForm.add(redioInactive, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 380, -1, -1));

        buttonGroup1.add(redioActive);
        redioActive.setFont(new java.awt.Font("Yu Gothic Light", 0, 24)); // NOI18N
        redioActive.setSelected(true);
        redioActive.setText("Active");
        ReForm.add(redioActive, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, 125, 41));

        lbGender.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        lbGender.setText("Status");
        ReForm.add(lbGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 175, 43));

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel9.setText("Employee Id");
        ReForm.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 223, 175, 42));

        txtType.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtType.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTypeActionPerformed(evt);
            }
        });
        txtType.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTypeKeyTyped(evt);
            }
        });
        ReForm.add(txtType, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 170, 440, 43));

        lbFirstName.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        lbFirstName.setText("Name");
        ReForm.add(lbFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 276, 155, 42));

        txtName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtName.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNameKeyTyped(evt);
            }
        });
        ReForm.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 279, 440, 43));

        txtUserName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtUserName.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserNameActionPerformed(evt);
            }
        });
        ReForm.add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 329, 440, 43));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel1.setText("User Name");
        ReForm.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 329, 175, 43));

        jLabel5.setBackground(new java.awt.Color(204, 0, 51));
        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Edite Details");
        jLabel5.setOpaque(true);
        ReForm.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 69));

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel10.setText("Type");
        ReForm.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 174, 175, 42));

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel11.setText("Search By");
        ReForm.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 111, 110, 41));

        comboSearch.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        comboSearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "User Name", "Employee Id", "Nic Number" }));
        ReForm.add(comboSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 111, 137, 45));

        txtSearch.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtSearch.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSearchKeyTyped(evt);
            }
        });
        ReForm.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 113, 290, 43));

        btnUpdte1.setBackground(new java.awt.Color(0, 102, 204));
        btnUpdte1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 36)); // NOI18N
        btnUpdte1.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdte1.setText("Update");
        btnUpdte1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUpdte1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUpdte1MouseExited(evt);
            }
        });
        btnUpdte1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdte1ActionPerformed(evt);
            }
        });
        ReForm.add(btnUpdte1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 500, 204, -1));

        txtEmployeeId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtEmployeeId.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtEmployeeId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmployeeIdActionPerformed(evt);
            }
        });
        txtEmployeeId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEmployeeIdKeyTyped(evt);
            }
        });
        ReForm.add(txtEmployeeId, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 226, 440, 43));

        jLayeredPane1.add(ReForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 780, 780));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 872, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 872, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserNameActionPerformed
        txtName.grabFocus();
    }//GEN-LAST:event_txtUserNameActionPerformed

    private void txtNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyTyped

    }//GEN-LAST:event_txtNameKeyTyped

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
       
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtTypeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTypeKeyTyped

    }//GEN-LAST:event_txtTypeKeyTyped

    private void txtTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTypeActionPerformed

    }//GEN-LAST:event_txtTypeActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void txtSearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchKeyTyped

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
      searchData();
    }//GEN-LAST:event_txtSearchKeyReleased

    private void btnUpdte1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdte1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdte1MouseEntered

    private void btnUpdte1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdte1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdte1MouseExited

    private void btnUpdte1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdte1ActionPerformed
       updateDetails();
    }//GEN-LAST:event_btnUpdte1ActionPerformed

    private void txtEmployeeIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmployeeIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmployeeIdActionPerformed

    private void txtEmployeeIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmployeeIdKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmployeeIdKeyTyped

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
             if(evt.getClickCount()==2){
            txtSearch.setText(jList1.getSelectedValue().split("-")[0]);
            jScrollPane1.setVisible(false);
            searchDetails();

        }
    }//GEN-LAST:event_jList1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Edite_user_Acc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Edite_user_Acc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Edite_user_Acc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Edite_user_Acc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Edite_user_Acc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane ReForm;
    private javax.swing.JButton btnUpdte1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> comboSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbFirstName;
    private javax.swing.JLabel lbGender;
    private javax.swing.JRadioButton redioActive;
    private javax.swing.JRadioButton redioInactive;
    private javax.swing.JTextField txtEmployeeId;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtType;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables

    private void searchData() {
       if(comboSearch.getSelectedItem()=="User Name"){
        try {
            if(!txtSearch.getText().trim().equals("")){
                ResultSet rs=  DB.search("SELECT * FROM user_account WHERE user_name LIKE '"+txtSearch.getText().toUpperCase()+"%'");
                Vector v = new Vector();
                       jScrollPane1.setVisible(false);
                while(rs.next()){
                     jScrollPane1.setVisible(true);
                    v.add(rs.getString("employee_id")+"-"+rs.getString("user_name"));
                }
                jList1.setListData(v);
            }else{
            jScrollPane1.setVisible(false);
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
       }else if(comboSearch.getSelectedItem()=="Employee Id"){
        try {
            if(!txtSearch.getText().trim().equals("")){
                ResultSet rs=  DB.search("SELECT * FROM user_account WHERE employee_id LIKE '"+txtSearch.getText().toUpperCase()+"%'");
                Vector v = new Vector();
                       jScrollPane1.setVisible(false);
                while(rs.next()){
                     jScrollPane1.setVisible(true);
                    v.add(rs.getString("employee_id")+"-"+rs.getString("user_name"));
                }
                jList1.setListData(v);
            }else{
              jScrollPane1.setVisible(false);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
       
       }else if(comboSearch.getSelectedItem()=="Nic Number"){
            try {
            if(!txtSearch.getText().trim().equals("")){
                ResultSet rs=  DB.search("SELECT * FROM employee WHERE nic_number LIKE '"+txtSearch.getText().toUpperCase()+"%'");
                Vector v = new Vector();
                       jScrollPane1.setVisible(false);
                while(rs.next()){
                     jScrollPane1.setVisible(true);
                    v.add(rs.getString("employee_id")+"-"+rs.getString("first_name")+" "+rs.getString("last_name"));
                }
                jList1.setListData(v);
            }else{
             jScrollPane1.setVisible(false);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
       
       }
    }

 

    private void editable() {
      txtType.setEditable(false);
      txtName.setEditable(false);
      txtUserName.setEditable(false);
      txtEmployeeId.setEditable(false);
     
    }

    private void searchDetails() {
        try {
            ResultSet search = DB.search("SELECT * FROM user_account WHERE employee_id='"+txtSearch.getText().toUpperCase()+"'");
            if(search.next()){
                ResultSet search1 = DB.search("SELECT * FROM account_type WHERE acc_code='"+search.getString("account_code")+"'");
             if(search1.next()){
             txtType.setText(search1.getString("acc_type"));
             }
            txtEmployeeId.setText(search.getString("employee_id"));
                ResultSet search2 = DB.search("SELECT * FROM employee WHERE employee_id='"+search.getString("employee_id")+"'");
           if(search2.next()){
           txtName.setText(search2.getString("first_name")+" "+search2.getString("last_name"));
           }
            txtUserName.setText(search.getString("user_name"));
            if(search.getInt("status")==1){
            redioActive.setSelected(true);
            }else{
            redioInactive.setSelected(true);
            }
            }
            
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void updateDetails() {
        if(redioActive.isSelected()){
            try {
                 DB.iud("update user_account set status='"+"1"+"' where employee_id='"+txtSearch.getText()+"'");
                  JOptionPane.showMessageDialog(this, "Active now "+ txtUserName.getText()+" user account !!! ");
                    clearFeald();
            } catch (Exception e) {
            }
            
        }else if(redioInactive.isSelected()){
            try {
                 DB.iud("update user_account set status='"+"0"+"' where employee_id='"+txtSearch.getText()+"'");
                 JOptionPane.showMessageDialog(this, "Inactive now "+ txtUserName.getText()+" user account !!! ");
                    clearFeald();
            } catch (Exception e) {
            }
        }
    }

    private void clearFeald() {
        txtEmployeeId.setText(null);
        txtName.setText(null);
        txtSearch.setText(null);
        txtType.setText(null);
        txtUserName.setText(null);
        redioActive.setSelected(true);
        txtSearch.grabFocus();
    }
}
