/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rent_item;

import common.DB;
import common.CommonM;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author geeth
 */
public class Delete_Rent_order extends javax.swing.JFrame {

    /**
     * Creates new form Start_Job
     */
    public Delete_Rent_order() {
        initComponents();
      jScrollPane2.setVisible(false);
      txtSearch.grabFocus();
      
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        CommonM.tableSettings(tb3);
        textFealds();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane2 = new javax.swing.JLayeredPane();
        ReForm = new javax.swing.JLayeredPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        lbFirstName = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        txtCustomerId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tb3 = new javax.swing.JTable();
        comboSearch = new javax.swing.JComboBox<>();
        btnStart1 = new javax.swing.JButton();
        txtOrderId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnStart2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLayeredPane2.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jLayeredPane2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ReForm.setBackground(new java.awt.Color(255, 255, 255));
        ReForm.setOpaque(true);
        ReForm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jList1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jList1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jList1KeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jList1);

        ReForm.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 280, -1));

        lbFirstName.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        lbFirstName.setText("Search By");
        ReForm.add(lbFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 175, 42));

        txtSearch.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtSearch.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSearchKeyTyped(evt);
            }
        });
        ReForm.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 280, 43));

        txtCustomerId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtCustomerId.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtCustomerId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerIdActionPerformed(evt);
            }
        });
        txtCustomerId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCustomerIdKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCustomerIdKeyTyped(evt);
            }
        });
        ReForm.add(txtCustomerId, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 450, 43));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel1.setText("Customer Id/Name");
        ReForm.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 200, 43));

        jLabel5.setBackground(new java.awt.Color(204, 0, 51));
        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Delete Rent Order");
        jLabel5.setOpaque(true);
        ReForm.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 69));

        tb3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Id", "Model", "Product Number", "Discription"
            }
        ));
        tb3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tb3MousePressed(evt);
            }
        });
        jScrollPane7.setViewportView(tb3);

        ReForm.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 660, 390));

        comboSearch.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        comboSearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NIC Number", "Customer Name", "Order Id" }));
        ReForm.add(comboSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, -1, 40));

        btnStart1.setBackground(new java.awt.Color(0, 102, 204));
        btnStart1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 30)); // NOI18N
        btnStart1.setForeground(new java.awt.Color(255, 255, 255));
        btnStart1.setText("Delete");
        btnStart1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnStart1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnStart1MouseExited(evt);
            }
        });
        btnStart1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStart1ActionPerformed(evt);
            }
        });
        ReForm.add(btnStart1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 700, 210, 60));

        txtOrderId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtOrderId.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtOrderId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrderIdActionPerformed(evt);
            }
        });
        txtOrderId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtOrderIdKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtOrderIdKeyTyped(evt);
            }
        });
        ReForm.add(txtOrderId, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 450, 43));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel2.setText("Order Id");
        ReForm.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 200, 43));

        btnStart2.setBackground(new java.awt.Color(0, 102, 204));
        btnStart2.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 30)); // NOI18N
        btnStart2.setForeground(new java.awt.Color(255, 255, 255));
        btnStart2.setText("Clear");
        btnStart2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnStart2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnStart2MouseExited(evt);
            }
        });
        btnStart2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStart2ActionPerformed(evt);
            }
        });
        ReForm.add(btnStart2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 700, 210, 60));

        jLayeredPane2.add(ReForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 750, 840));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 881, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        
    }//GEN-LAST:event_txtSearchActionPerformed

    private void txtSearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyTyped

    }//GEN-LAST:event_txtSearchKeyTyped

    private void txtCustomerIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerIdActionPerformed
        txtSearch.grabFocus();
    }//GEN-LAST:event_txtCustomerIdActionPerformed

    private void txtCustomerIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCustomerIdKeyReleased
    

    }//GEN-LAST:event_txtCustomerIdKeyReleased

    private void txtCustomerIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCustomerIdKeyTyped

    }//GEN-LAST:event_txtCustomerIdKeyTyped

    private void tb3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb3MousePressed

    }//GEN-LAST:event_tb3MousePressed

    private void btnStart1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStart1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStart1MouseEntered

    private void btnStart1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStart1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStart1MouseExited

    private void btnStart1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStart1ActionPerformed
      deleteOrder();
    }//GEN-LAST:event_btnStart1ActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
           if (evt.getClickCount() == 2) {
            click();
        }
    }//GEN-LAST:event_jList1MouseClicked

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
          searchPro();
        if (evt.getKeyCode() == 40) {
            jList1.setSelectedIndex(0);
            jList1.grabFocus();
        }
        if (txtSearch.getText().equals("")) {
            clearFeald();
        }
    }//GEN-LAST:event_txtSearchKeyReleased

    private void jList1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jList1KeyPressed
        if (evt.getKeyCode() == 10) {
            click();
        }
    }//GEN-LAST:event_jList1KeyPressed

    private void txtOrderIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrderIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrderIdActionPerformed

    private void txtOrderIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOrderIdKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrderIdKeyReleased

    private void txtOrderIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOrderIdKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrderIdKeyTyped

    private void btnStart2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStart2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStart2MouseEntered

    private void btnStart2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStart2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStart2MouseExited

    private void btnStart2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStart2ActionPerformed
       clearFeald();
    }//GEN-LAST:event_btnStart2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Delete_Rent_order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Delete_Rent_order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Delete_Rent_order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Delete_Rent_order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Delete_Rent_order().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane ReForm;
    private javax.swing.JButton btnStart1;
    private javax.swing.JButton btnStart2;
    public static javax.swing.JComboBox<String> comboSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLayeredPane jLayeredPane2;
    public static javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JLabel lbFirstName;
    public static javax.swing.JTable tb3;
    public static javax.swing.JTextField txtCustomerId;
    public static javax.swing.JTextField txtOrderId;
    public static javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables



    private void textFealds() {
        txtCustomerId.setEditable(false);
        txtOrderId.setEditable(false);
        tb3.setEnabled(false);
        
    }
    private void claerTable() {
          DefaultTableModel dtm1 = (DefaultTableModel) tb3.getModel();
          dtm1.setRowCount(0);
          txtCustomerId.setText(null);
          txtSearch.setText(null);
         
    }

    
        private void click() {
        try {
            jScrollPane2.setVisible(false);
            if (comboSearch.getSelectedItem().equals("NIC Number")) {
                ResultSet search1 = DB.search("SELECT * FROM rent_order WHERE status= 1 AND customer_id='" + jList1.getSelectedValue().split("-")[0] + "'");
                if (search1.next()) {
                    searchDetails(search1.getString("order_id"));
                } else {
                    JOptionPane.showMessageDialog(this, "This customer have not active job");
                    txtSearch.setText("");
                    txtSearch.grabFocus();
                }
            } else if (comboSearch.getSelectedItem().equals("Order Id")) {
                     String OrderId=jList1.getSelectedValue();
                    searchDetails(OrderId);
//                } else {
//                    JOptionPane.showMessageDialog(this, "This customer have not active job");
//                    txtSearch.setText("");
//                    txtSearch.grabFocus();
//                }

            } else if (comboSearch.getSelectedItem().equals("Customer Name")) {
                ResultSet search1 = DB.search("SELECT * FROM rent_order WHERE status= 1 AND customer_id='" + jList1.getSelectedValue().split("-")[0] + "'");
                if (search1.next()) {
                    searchDetails(search1.getString("order_id"));
                } else {
                    JOptionPane.showMessageDialog(this, "This customer have not active job");
                    txtSearch.setText("");
                    txtSearch.grabFocus();
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
        
         private void searchPro() {
        try {
            if (!txtSearch.getText().trim().equals("")) {
                if (comboSearch.getSelectedItem().equals("NIC Number")) {
                    ResultSet rs = DB.search("SELECT * FROM customer WHERE status=1 AND nic_number LIKE '" + txtSearch.getText().toUpperCase() + "%'");
                    Vector v = new Vector();
                    jScrollPane2.setVisible(false);
                    while (rs.next()) {
                        jScrollPane2.setVisible(true);
                        v.add(rs.getString("customer_id") + "-" + rs.getString("first_name") + " " + rs.getString("last_name"));
                        jList1.setListData(v);
                    }
                } else if (comboSearch.getSelectedItem().equals(("Order Id"))) {
                    ResultSet rs = DB.search("SELECT * FROM rent_order WHERE status=1 AND order_id LIKE '" + txtSearch.getText().toUpperCase() + "%'");
                    Vector v = new Vector();
                    jScrollPane2.setVisible(false);
                    while (rs.next()) {
                        jScrollPane2.setVisible(true);
                        v.add(rs.getString("order_id"));
                    }
                    jList1.setListData(v);
                } else if (comboSearch.getSelectedItem().equals("Customer Name")) {
                    ResultSet rs = DB.search("SELECT * FROM customer WHERE status=1 AND first_name LIKE '" + txtSearch.getText().toUpperCase() + "%'");
                    Vector v = new Vector();
                    jScrollPane2.setVisible(false);
                    while (rs.next()) {
                        jScrollPane2.setVisible(true);
                        v.add(rs.getString("customer_id") + "-" + rs.getString("first_name") + " " + rs.getString("last_name"));
                    }
                    jList1.setListData(v);

                }
            } else {
                jScrollPane2.setVisible(false);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
         
         
           private void searchDetails(String orderId) {
        try {
            String customerId = jList1.getSelectedValue().split("-")[0];
            ResultSet search4 = DB.search("SELECT * FROM rent_order WHERE status=1 AND customer_id='" + customerId + "'");
            int i = 0;
            while (search4.next()) {
                i++;
            }
            if (i == 1) {
                ResultSet search = DB.search("SELECT * FROM rent_order WHERE status=1 AND order_id='" + orderId + "'");
                if (search.next()) {
                    ResultSet search1 = DB.search("SELECT * FROM customer WHERE customer_id='" + search.getString("customer_id") + "'");
                    if (search1.next()) {
                        txtCustomerId.setText(search.getString("customer_id") + "-" + search1.getString("first_name") + " " + search1.getString("last_name"));
                        txtSearch.setText(search1.getString("nic_number"));
                        txtOrderId.setText(orderId);
                        comboSearch.setSelectedIndex(0);
                    }

                    ResultSet search2 = DB.search("SELECT * FROM rent_order_item WHERE order_id='" + orderId + "'");
                    DefaultTableModel dtm = (DefaultTableModel) tb3.getModel();
                    dtm.setRowCount(0);
                    while (search2.next()) {
                        Vector v = new Vector();
                        ResultSet search3 = DB.search("SELECT * FROM rent_item WHERE item_id='" + search2.getString("item_id") + "'");
                        if (search3.next()) {
                            v.add(search2.getString("item_id") + "-" + search3.getString("name"));
                            v.add(search3.getString("model"));
                            v.add(search3.getString("product_number"));
                            
                            v.add(search.getString("discription"));
                            dtm.addRow(v);
                        }
                    }
                }
            } else if (i > 1) {
                new Job_Selection_Delete_Order().setVisible(true);

            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void deleteOrder() {
        try {
            
            if(!txtOrderId.getText().equals("")){
            int input = JOptionPane.showConfirmDialog(null, "Do you want to delete this order?");
            if(input==0){
            DB.iud("UPDATE rent_order SET status='"+2+"' WHERE order_id='"+txtOrderId.getText()+"'");
            DB.iud("UPDATE rent_order_item SET status='"+2+"' WHERE order_id='"+txtOrderId.getText()+"'");
            clearFeald();
            }
            }else{
            JOptionPane.showMessageDialog(this, "Please search details", "Error", JOptionPane.ERROR_MESSAGE);
            }
                   
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void clearFeald() {
       txtCustomerId.setText(null);
       txtOrderId.setText(null);
       txtSearch.setText(null);
       claerTable();
    }

   
}
