/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rent_item;


import static com.rent_item.End_Order.comboSearch;
import static com.rent_item.End_Order.txtCustomer;
import static com.rent_item.End_Order.txtCustomerPayment;
import static com.rent_item.End_Order.txtOrderId;
import static com.rent_item.End_Order.txtSearch;
import com.work_order.*;
import static com.work_order.Paymets.txtOrderId;
import common.CommonM;
import common.DB;
import java.awt.Color;
import java.math.BigDecimal;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import java.util.concurrent.TimeUnit;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author geeth
 */
public class Job_Selection_End_Rent extends javax.swing.JFrame {

    /**
     * Creates new form Add_Customer_Befor_Start
     */
    public Job_Selection_End_Rent() {
        initComponents();
        addJob();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        ReForm = new javax.swing.JLayeredPane();
        lbFirstName = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ReForm.setBackground(new java.awt.Color(255, 255, 255));
        ReForm.setOpaque(true);

        lbFirstName.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        lbFirstName.setText("Select Job Vehicle");

        jLabel5.setBackground(new java.awt.Color(204, 0, 51));
        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Job Selection");
        jLabel5.setOpaque(true);

        btnRegister.setBackground(new java.awt.Color(0, 102, 204));
        btnRegister.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 36)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(255, 255, 255));
        btnRegister.setText("Select");
        btnRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegisterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegisterMouseExited(evt);
            }
        });
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        ReForm.setLayer(lbFirstName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ReForm.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ReForm.setLayer(btnRegister, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ReForm.setLayer(jComboBox1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout ReFormLayout = new javax.swing.GroupLayout(ReForm);
        ReForm.setLayout(ReFormLayout);
        ReFormLayout.setHorizontalGroup(
            ReFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReFormLayout.createSequentialGroup()
                .addGroup(ReFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(ReFormLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lbFirstName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(ReFormLayout.createSequentialGroup()
                        .addGap(470, 470, 470)
                        .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ReFormLayout.setVerticalGroup(
            ReFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReFormLayout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(ReFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(btnRegister))
        );

        jLayeredPane1.add(ReForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 710, 290));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 794, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
       addData();
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnRegisterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegisterMouseExited
        CommonM.setDefaultColor(btnRegister);
    }//GEN-LAST:event_btnRegisterMouseExited

    private void btnRegisterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegisterMouseEntered
        CommonM.setBlue(btnRegister);
    }//GEN-LAST:event_btnRegisterMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Job_Selection_End_Rent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Job_Selection_End_Rent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Job_Selection_End_Rent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Job_Selection_End_Rent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Job_Selection_End_Rent().setVisible(true);

            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane ReForm;
    private javax.swing.JButton btnRegister;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel lbFirstName;
    // End of variables declaration//GEN-END:variables

    private void addJob() {
      //  if (Paymets.comboSearch.getSelectedItem().equals("NIC Number")) {
            try {
                String search = End_Order.jList1.getSelectedValue().split("-")[0];
                ResultSet search1 = DB.search("SELECT * FROM rent_order WHERE customer_id='" + search + "'");
                while (search1.next()) {
                        String date = search1.getString("data_time").split("-")[0] + "-" + search1.getString("data_time").split("-")[1] + "-" + search1.getString("data_time").split("-")[2] + ")";
                        jComboBox1.addItem(search1.getString("order_id") + "-" + "(Date:" + date);
                    
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
       // }
    }

    private void addData() {
        try {
            String orderId=jComboBox1.getSelectedItem().toString().split("-")[0];
            System.out.println(orderId);
                     ResultSet search = DB.search("SELECT * FROM rent_order WHERE status=1 AND order_id='" + orderId + "'");
                 if(search.next()){
                End_Order.txtOrderId.setText(orderId);
                ResultSet search1 = DB.search("SELECT * FROM customer WHERE customer_id='" + search.getString("customer_id") + "'");
                if (search1.next()) {
                    txtCustomer.setText(search.getString("customer_id") + "-" + search1.getString("first_name") + " " + search1.getString("last_name"));
                    txtSearch.setText(search1.getString("nic_number"));
                    comboSearch.setSelectedIndex(0);
                }
                
                ResultSet search2 = DB.search("SELECT * FROM rent_order_item WHERE order_id='"+orderId+"'");
                 DefaultTableModel dtm =(DefaultTableModel) End_Order.tb4.getModel();
                 dtm.setRowCount(0);
                while(search2.next()){
               Vector v = new Vector();
                    ResultSet search3 = DB.search("SELECT * FROM rent_item WHERE item_id='"+search2.getString("item_id")+"'");
                    if(search3.next()){
                    v.add(search2.getString("item_id")+"-"+search3.getString("name"));
                    v.add(search3.getString("model"));
                    v.add(search3.getString("product_number"));
                    v.add(dayCalculate(search.getString("data_time")));
                    if(search3.getString("status").equals("1")){
                    v.add("Uncomplite");
                    
                    }else{
                    v.add("Complite");
                    }
                    v.add(loadPaymentStatus(search2.getString("item_id"),orderId));
                    dtm.addRow(v);
                    }
                    
                }
                     loadPayment(orderId);
                     this.dispose();
                 }
        } catch (Exception e) {
            e.printStackTrace();
        }
              
    }
    
    
    
     private String dayCalculate(String orderDate) {
         String retunVal=null;
        try {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");         
        String curunt = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss ").format(new Date());
           long cd= sdf.parse(curunt).getTime();
           String orderDate1 =orderDate;
            long rd= sdf.parse(orderDate1).getTime();
            long dif =Math.abs(sdf.parse(orderDate1).getTime()-sdf.parse(curunt).getTime());
            long convert =TimeUnit.MILLISECONDS.convert(dif, TimeUnit.SECONDS);
            long convert1=TimeUnit.HOURS.convert(dif, TimeUnit.MILLISECONDS);
           
            if(convert1>24){
                retunVal=String.valueOf(convert1/24)+" Days";
            }else{
            retunVal="1 Day";
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    return retunVal;
    }
    private void loadPayment(String orderId) {
        try {
              Double payment = 0.00;
            ResultSet search = DB.search("SELECT * FROM payment WHERE order_id='" + orderId + "'");
            while (search.next()) {
                payment = payment + search.getDouble("amount");
                System.out.println(payment);
            }
            String setValue = String.valueOf(payment);
            BigDecimal bd = new BigDecimal(setValue);
            DecimalFormat formatterBd = new DecimalFormat("##.00");
            if (payment == 0.00) {
                End_Order.txtCustomerPayment.setText("0.00");
            } else {
                End_Order.txtCustomerPayment.setText(formatterBd.format(bd));
            }
        } catch (Exception e) {
            e.printStackTrace();
       }
    }
    
    private String loadPaymentStatus(String itemId,String orderId) {
        String result=null;
        try {
            ResultSet search = DB.search("SELECT * FROM rent_item_payment WHERE order_id='"+orderId+"' AND item_id='"+itemId+"'");
            if(search.next()){
                   DefaultTableModel dtm = (DefaultTableModel) End_Order.tb3.getModel();
                    dtm.setRowCount(0);
                        Vector v = new Vector();
                        v.add(search.getString("item_id"));
                        v.add(search.getString("amount_per_date"));
                        v.add(search.getString("amount"));
                        v.add(search.getString("Discount"));
                        v.add(String.valueOf(Double.parseDouble(search.getString("amount"))-Double.parseDouble(search.getString("discount"))));
                        dtm.addRow(v);
                        result="Added";
            }else{
            result="Pending.......";
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        return result;
    }
 
}